# Generated by Django 3.2.7 on 2021-10-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pack',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='pack',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='pack',
            old_name='modifiedAt',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='buyerCard',
            new_name='buyer_card',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='buyerCardCVV',
            new_name='buyer_card_cvv',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='buyerCardDueDate',
            new_name='buyer_card_due_date',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='buyerCardName',
            new_name='buyer_card_name',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='buyerID',
            new_name='buyer_id',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='birthDay',
            new_name='birth_day',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='pack',
            name='image_url',
            field=models.CharField(default='https://cdn.pixabay.com/photo/2017/01/05/16/57/girl-1955797_960_720.jpg', max_length=255),
        ),
    ]
